import Head from 'next/head'
import GenderCategory from '../components/GenderCategorySection'
import Slider from '../components/HomePageSlider'
import NewProducts from '../components/NewProducts'
import styles from '../styles/pages-css/Home.module.css'
import { getProducts } from "./api/apiCalls/getProducts"

export default function Home({products}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider/>
      <div className= {styles.body}>
        <GenderCategory/>
        <NewProducts products= {products}/>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const URL = `http://localhost:3000/api/products/new`
  const products = await getProducts(URL)
  return {
    props:{
      products: products
    }
    
  }
}