import Head from 'next/head'
import GenderCategory from '../components/GenderCategorySection'
import Slider from '../components/HomePageSlider'
import NewProducts from '../components/NewProducts'
import styles from '../styles/pages-css/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider/>
      <div className= {styles.body}>
        <GenderCategory/>
        <NewProducts/>
      </div>
    </div>
  )
}
